import { GvmPageData } from './gvm-content';

const nav = [
  ['About GVM', '/about'], ['Activities', '/activities'], ['Gau Shala', '/gaushala'],
  ['Bal Griha', '/bal-griha'], ['Our Team', '/team'], ['Contact', '/contact'],
];

export function SiteHeader() {
  return <header className="gvm-nav"><a className="gvm-brand" href="/">GANDHI VIDYA MANDIR</a><nav>{nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><a className="gvm-support" href="/support-us">Support us <b>↗</b></a></header>;
}

export function SiteFooter() {
  return <footer className="gvm-footer"><div><strong>GANDHI VIDYA MANDIR</strong><p>Sardarshahr, Churu<br/>Rajasthan 331401, India</p></div><div><span>CONTACT</span><a href="mailto:gvmcentraloffice@gmail.com">gvmcentraloffice@gmail.com</a><a href="tel:+911564220025">01564-220025 / 223642 / 223054</a></div><div><span>EXPLORE</span><a href="/activities">Activities</a><a href="/contact">Contact</a><a href="https://www.gandhividyamandir.org/">Official website ↗</a></div></footer>;
}

export function GvmPage({ page }: { page: GvmPageData }) {
  const isAbout = page.kicker === 'ABOUT GVM';
  return <main className="gvm-site"><SiteHeader/><section className="gvm-page-hero"><img src={page.image} alt="Gandhi Vidya Mandir campus activity"/><div><span>{page.kicker}</span><h1>{page.title}</h1><p>{page.lead}</p></div></section><section className="gvm-page-body">{page.sections.map((section, index) => <article className="gvm-content-block" key={section.heading}><span>0{index + 1}</span><div><h2>{section.heading}</h2>{section.text.map(text => <p key={text}>{text}</p>)}{section.bullets && <ul>{section.bullets.map(item => <li key={item}>{item}</li>)}</ul>}</div></article>)}</section>{isAbout && <><section className="mission-section"><div className="shell"><div className="mission-heading"><span className="mono">GVM · SERVICE WITH SINCERITY</span><h2>Our mission</h2></div><div className="mission-copy"><p>Gandhi Vidya Mandir (GVM) signifies an educational establishment that sows the seed of humanism into each human being. If I were to elaborate, ‘Gandhi Vidya’ would augment a life-style that is useful to all and benign to all; that would keep the human society held together despite diversity of views, environments and aptitudes, by an abiding bond of love; and that should, as well, be able to prevent degeneration of human society by providing equitable education of the highest order in different streams of knowledge. That would also foster rural upliftment, character building, creation of addiction-free society, self-purification, awareness for health and hygiene, “think no ill – do no ill” to anyone, and an urge to extend a helping hand in fulfilling the basic needs (of the society). I would call it GANDHI VIDYA, and its veritable sanctum would be MANDIR.</p><blockquote><span>॥ कुछ ना चाहो | काम आ जाओ ॥<br/>॥ कोई और नहीं | कोई गैर नहीं ॥</span><strong>-Swami Shri Ramsharanji</strong><small>Formerly Shri Kanhaiyalal Dugar<br/>Our Founder</small></blockquote></div></div></section><section className="story section shell" id="stories"><div className="story-art"><div className="frame"><img className="story-photo" src="/gh.avif" alt="Swami Shri Ram Sharanji"/></div></div><div className="story-copy"><div className="eyebrow mono">GAU SHALA THAT LIVE ON</div><h2>A life given<br/>to <em>service</em></h2><p>Inspired by Swami Shri Ramsharanji and Gandhian ideals, GVM believes learning becomes meaningful when it uplifts people, families and communities.</p><a className="pill" href="/gaushala">Explore the GVM story <span>↗</span></a></div></section></>}<section className="gvm-page-cta"><p>GANDHI VIDYA MANDIR · SARDARSHAHR, RAJASTHAN</p><h2>Education with<br/><em>social commitment.</em></h2><a href="/support-us">Support our cause <b>↗</b></a></section><SiteFooter/></main>;
}
