import { imageUrls } from './gvm-content';
import { SiteFooter, SiteHeader } from './gvm-page';

export default function Home() {
  return <main className="gvm-site"><SiteHeader/>
    <section className="gvm-home-hero"><img src={imageUrls.home} alt="Gandhi Vidya Mandir"/><div className="gvm-home-copy"><span>SARDARSHAHR, RAJASTHAN · SINCE 1950</span><h1>Education<br/><em>maketh a man.</em></h1><p>Gandhi Vidya Mandir is an educational and social-service institution in the Thar Desert, committed to learning, dignity and rural upliftment.</p><a href="/about">Discover GVM <b>↗</b></a></div></section>
    <section className="gvm-intro"><span>THE GVM STORY</span><div><h2>From desert land<br/>to an <em>oasis of learning.</em></h2><p>Founded in 1950 on 1,200 acres at Sardarshahr, GVM has grown into a campus of education, health, welfare, research and service. It serves learners from pre-primary schooling to doctoral study and extends its work into villages and communities.</p></div></section>
    <section className="gvm-stats"><div><b>1950</b><span>Founded in Sardarshahr</span></div><div><b>1,200</b><span>Acres of campus and community</span></div><div><b>10,000+</b><span>Resident and non-resident students</span></div><div><b>5</b><span>Schools alongside higher education</span></div></section>
    <section className="gvm-mission"><div className="gvm-image-panel"><img src={imageUrls.campus} alt="Gandhi Vidya Mandir campus"/></div><div><span>OUR MISSION</span><h2>Knowledge. Emotion.<br/><em>Conduct. Growth.</em></h2><p>The education imparted through GVM and IASE University embraces the four facets of human personality: knowledge, emotion, conduct and physical development.</p><p>Its vision is education that nurtures ethics, values, humanism and social responsibility—useful to individuals, families and society alike.</p><a href="/about">Read about GVM <b>↗</b></a></div></section>
    <section className="gvm-service"><span>SERVICE WITH SINCERITY</span><h2>Education that reaches<br/><em>beyond the classroom.</em></h2><div className="gvm-service-grid"><article><b>01</b><h3>Education & Research</h3><p>IASE University, schools, teacher education, medicine, engineering, life sciences, IT, management and distance learning.</p><a href="/activities">Explore activities ↗</a></article><article><b>02</b><h3>Rural & Health Welfare</h3><p>Medical centres, village health camps, literacy, vocational programmes, water conservation and agricultural training.</p><a href="/activities">See community work ↗</a></article><article><b>03</b><h3>Care & Compassion</h3><p>Bal Griha, Gau Shala, social welfare homes and relief efforts embody GVM’s commitment to serving people and animals in need.</p><a href="/bal-griha">Visit Bal Griha ↗</a></article></div></section>
    <section className="gvm-founder"><div><span>OUR INSPIRATION</span><h2>A life given<br/><em>to service.</em></h2><p>Shri Kanhaiyalal Dugar—later Swami Shri Ramsharanji—dedicated his life and personal wealth to education and the upliftment of the disadvantaged. His Gandhian ideals remain at the heart of GVM.</p><a href="/about">Explore the founding vision <b>↗</b></a></div><img src={imageUrls.founder} alt="Swami Shri Ramsharanji"/></section>
    <section className="gvm-testimonials"><span>VOICES OF ENCOURAGEMENT</span><blockquote>“I would be glad when this institution shall develop into an ideal University, progressively serving humanity at large through education and culture.”<footer>— Dr. Rajendra Prasad, first President of India</footer></blockquote><blockquote>“Service with Sincerity”<footer>— Gandhi Vidya Mandir watchword</footer></blockquote></section>
    <section className="gvm-gallery"><img src={imageUrls.activities} alt="GVM education and extension"/><img src={imageUrls.gaushala} alt="GVM Gau Shala"/><img src={imageUrls.campus} alt="GVM campus"/></section>
    <section className="gvm-home-support"><span>SUPPORT OUR CAUSE</span><h2>Help education<br/><em>serve humanity.</em></h2><p>Support GVM’s work in education, health, welfare, rural development and compassionate care.</p><a href="/support-us">Support GVM <b>↗</b></a></section>
    <SiteFooter/>
  </main>;
}